# This is the top-level variable file that will be used for the FlexPod setup. 
#
# Setting the following variables to anything but 'true' ('false' is suggested when not using 'true'), will cause the 
# This needs to setup in this case to have local boot with NVMe-TCP and NFS storage protocols.
# protocol to not be configured.
configure_nvme_tcp: 'true'  
configure_nfs: 'true'       # In FlexPod, nfs is always used unless you have an All SAN Array (ASA)
#
# Update the the following lines to setup NTP Server(s)
# Note that we are setting up NTP Distribution on the Nexus switches and the first two NTP servers are Nexus Switch mgmt0 IP addresses.
ntp_servers:
  - ip_address: "192.168.1.51"
  - ip_address: "192.168.1.52"
  - ip_address: "192.168.1.53"

ib_mgmt_ntp_servers:                # InBand Management NTP Addresses to be used by ESXi hosts and VMs
  - ip_address: "192.168.1.13"
  - ip_address: "192.168.1.14"

# Update the the following lines to setup DNS Server(s)
# Note: The Nexus scripts assume exactly 2 DNS servers.
dns_servers:
  - ip_address: "192.168.1.51"
  - ip_address: "192.168.1.52"

# DNS Domain Name
dns_domain_name: "flexpodb4.cisco.com"

# Update the the following line to setup Timezone
time_zone: 'America/New_York'

#ESXi Host Names - These host names and identifiers will be used for creating the host NQNs list for NVMe/TCP config on NetApp end. 
#They can also be assigned as UCS Profile names.
nvme_esxi_hosts:
  - hostname: "express-esxi-1"
    nvme_nqn: "nqn.2014-08.com.flexpod:nvme:esx-01"
  - hostname: "express-esxi-2"
    nvme_nqn: "nqn.2014-08.com.flexpod:nvme:esx-02"

#
# This is the list of all the VLANs that will be defined on Nexus, Storage, UCS, and VMware
# VLAN Names are adjustable and can be modified in here
# Comment out any VLANs that are not used here and below(NVMe-TCP)
#
native_vlan_name: 'Native-Vlan' # Native VLAN
native_vlan_id: 1101
ib_vlan_name: 'IB-MGMT' # IN BAND Management VLAN
ib_vlan_id: 2229
vm_vlan_name: 'VM-Traffic' # VLAN to carry VM traffic on VDS
vm_vlan_id: 2231
vmotion_vlan_name: 'vMotion' # vMotion VLAN
vmotion_vlan_id: 2232
nfs_vlan_name: 'Infra-NFS' # NFS Traffic between ESXi and Storage
nfs_vlan_id: 2230
nvme_tcpA_vlan_name: 'Infra-NVMe-TCP-A' # NVMe-TCP-A VLAN (if needed)
nvme_tcpA_vlan_id: 2233
nvme_tcpB_vlan_name: 'Infra-NVMe-TCP-B' # NVMe-TCP-B VLAN (if needed)
nvme_tcpB_vlan_id: 2234
#
# lan_state should be set to 'present' to configure the objects
# In future, this parameter will be used for deleting the configuration
#
lan_state : 'present'
#
# VLAN Lists - Comment out or remove any VLANs not being used.
#
# The ib_mgmt_vlan_list contains one entry, the IB-MGMT VLAN.
#
ib_mgmt_vlan_list:
  - name: "{{ ib_vlan_name }}"
    id: "{{ ib_vlan_id }}"
    native: 'no'
    state: "{{lan_state}}"
#
# The storage_vlan_list contains VLANs that are configured on the storage controllers.
# These VLANs are also configured in the UCS and in the Nexus switches. This list has
# two extra fields, storage_protocol, and fabric. Do not remove these extra fields.
#
storage_vlan_list:
  - name: "{{ nfs_vlan_name }}"
    id: "{{ nfs_vlan_id }}"
    native: 'no'
    storage_protocol: NFS
    state: "{{lan_state}}"
  - name: "{{ nvme_tcpA_vlan_name }}"
    id: "{{ nvme_tcpA_vlan_id }}"
    native: 'no'
    storage_protocol: NVMe
    fabric: A
    state: "{{lan_state}}"
  - name: "{{ nvme_tcpB_vlan_name }}"
    id: "{{ nvme_tcpB_vlan_id }}"
    native: 'no'
    storage_protocol: NVMe
    fabric: B
    state: "{{lan_state}}"

# The remaining_vlan_list contains all vlans that are not configured on storage,
# but are configured in Nexus and UCS.
#
remaining_vlan_list:
  - name: "{{ native_vlan_name }}"
    id: "{{ native_vlan_id }}"
    native: 'yes'
    state: "{{lan_state}}"
  - name: "{{ vm_vlan_name }}"
    id: "{{ vm_vlan_id }}"
    native: 'no'
    state: "{{lan_state}}"
  - name: "{{ vmotion_vlan_name }}"
    id: "{{ vmotion_vlan_id }}"
    native: 'no'
    state: "{{lan_state}}"

# VLANs definitions below will be used to setup trunk ports on Nexus Switches
# all_vlans_list: for vpc_peer_link and UCS FI trunk ports
# These VLANs must be same or a subset of the vlan_list abovea
# Comment out or remove any VLANs that are not used (NVMe-TCP)
# In future, these values will be auto-generated
#
all_vlans_list: "{{ ib_vlan_id }},{{ vm_vlan_id }},{{ nfs_vlan_id }},{{ vmotion_vlan_id }},{{ nvme_tcpA_vlan_id }},{{ nvme_tcpB_vlan_id }}"
# storage_vlans_list: for storage uplink trunk ports
storage_vlans_list: "{{ ib_vlan_id }},{{ nfs_vlan_id }},{{ nvme_tcpA_vlan_id }},{{ nvme_tcpB_vlan_id }}"
# mgmt_vlans_list: for uplink/management switch trunk port
mgmt_vlans_list: "{{ ib_vlan_id }},{{ vm_vlan_id }}"
#
# VLAN/Portgroup List with Pinning info for VMware Distributed Switch vDSO for vMotion and Tenant Data/Storage
vds0_vlan_list:
  - name: "{{ nfs_vlan_name }}"
    # portgroup name will be configured in VMware
    portgroup_name: "{{ nfs_vlan_name }}-LACP"
    id: "{{ nfs_vlan_id }}"
    active_uplinks:
      - "lag1"
    standby_uplinks: []
  - name: "{{ vm_vlan_name }}"
    # portgroup name will be configured in VMware
    portgroup_name: "{{ vm_vlan_name }}-LACP"
    id: "{{ vm_vlan_id }}"
    active_uplinks: 
      - "lag1"
        #- "Uplink 2"
    standby_uplinks: []
  - name: "{{ vmotion_vlan_name }}"
    # portgroup name will be configured in VMware
    portgroup_name: "{{ vmotion_vlan_name }}-LACP"
    id: "{{ vmotion_vlan_id }}"
    active_uplinks: "lag1"
    standby_uplinks: []

nvme_tcp_vds_vlan_list:
  - name: "{{ nvme_tcpA_vlan_name }}"
    # portgroup name will be configured in VMware
    portgroup_name: "{{ nvme_tcpA_vlan_name }}-LACP"
    id: "{{ nvme_tcpA_vlan_id }}"
    active_uplinks:
      - "lag1"
    standby_uplinks: []
  - name: "{{ nvme_tcpB_vlan_name }}"
    # portgroup name will be configured in VMware
    portgroup_name: "{{ nvme_tcpB_vlan_name }}-LACP"
    id: "{{ nvme_tcpB_vlan_id }}"
    active_uplinks:
      - "lag1"
    standby_uplinks: []

nfs_portgroup: "VMKernel-Infra-NFS"
esxi_nfs_vlan: "{{ nfs_vlan_id }}"
#
# VMware Configurations
# provide the user names and passwords to connect to the ESXi servers
# and VMware vCenter
#
esxi_username: root
esxi_password: "{{ ansible_ssh_pass }}"
#
vcenter_dc: FlexPod-DC
vcenter_cluster: FlexPod-Management
#
vcenter_hostname: "10.102.1.100"
# e.g. vcenter_hostname: 10.50.160.100
vcenter_username: "administrator@vsphere.local"
# e.g. vcenter_username: administrator@vsphere.local
vcenter_password: "<password>"
# e.g. vcenter_password: "cisco!23"
#
# DVS Parameters; use version 8.0.3 for VMware 8.0U3 or above
#
dvs_name: "vDS0-LACP"
dv_version: "8.0.0"
dv_uplink: "2"
dv_protocol: "lldp"
dv_operation: "both"
