---
- name: "Create NTP Server Policy"
  vars:
    api_info: &api_info_NTP
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_rest_api:
    <<: *api_info_NTP
    resource_path: /ntp/Policies
    query_params:
       $filter: "Name eq '{{ name_of_NTP_server_policy }}'"
    api_body: {
        "Name": "{{ name_of_NTP_server_policy }}",
        "Description": "{{ description_of_NTP_server_policy }}",
        "Enabled": true,
        "NtpServers": ["{{ ntp_servers[0].ip_address }}","{{ ntp_servers[1].ip_address }}"],
        "Timezone": "{{ time_zone }}",
        "Organization": {
           "Moid": "{{ intersight_org.api_response.Moid }}"
         },
        Tags: [{Key: "configmode", Value: "ansible"},{Key: "prefix", Value: "{{ prefix }}"}]
     }
  register: ntp_policy
