---
- name: "Boot Order Policy"
  vars:
    api_info: &api_info_boot_policy
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  block:
  -    cisco.intersight.intersight_rest_api:
          <<: *api_info_boot_policy
          resource_path: /boot/PrecisionPolicies
          query_params:
             $filter: "Name eq '{{ boot_order_policy_name }}'"
          api_body: {
            "Name": "{{ boot_order_policy_name }}",
            "Description": "{{ boot_order_policy_description }}",

            "Organization": {
               "Moid": "{{ intersight_org.api_response.Moid }}"
             },
            Tags: [{Key: "configmode", Value: "ansible"},{Key: "prefix", Value: "{{ prefix }}"}],

             "ConfiguredBootMode": "{{ boot_mode }}",
             "EnforceUefiSecureBoot": "{{ enable_uefi_secureboot|bool }}",
             "BootDevices": [
                {
                   "Name": "{{ Name_of_LocalDisk }}",
                   "ClassId": "boot.LocalDisk",
                   "Enabled": "{{ EnableLocalDisk|bool }}",
                   "ObjectType": "boot.LocalDisk",
                   "Slot": "{{ LocalDisk_Slot }}"
                },
                {
                   "Name": "{{ Name_of_VirtualMedia }}",
                   "ClassId": "boot.VirtualMedia",
                   "Enabled": "{{ Enable_VirtualMedia_boot_device|bool }}",
                   "ObjectType": "boot.VirtualMedia",
                   "Subtype": "{{ VirtualMedia_Subtype }}"
                },
             ]
            }
       register: boot_policy
