---
- name: "Configure Ethernet Network Policies"
  vars:
    api_info: &api_info_mgmt
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  block:
  - name: "Configure Ethernet Network Policies for native vlan"
    cisco.intersight.intersight_rest_api:
      <<: *api_info_mgmt
      resource_path: /vnic/EthNetworkPolicies
      query_params:
         $filter: "Name eq '{{ name_of_network_policy_native }}'"
      api_body: {
        "Name": "{{ name_of_network_policy_native }}",
        "Description": "{{ description_of_network_policy_native }}",

        "Organization": {
           "Moid": "{{ intersight_org.api_response.Moid }}"
         },
        Tags: [{Key: "configmode", Value: "ansible"},{Key: "prefix", Value: "{{ prefix }}"}],
        "VlanSettings": {
           "Mode": "TRUNK",
           "DefaultVlan": "{{ native_vlan_id }}",
           "AllowedVlans": ""
           }
        }
    register: management_network_policy_native

  - name: "Configure Ethernet Network Policies for IB-mgmt vlan"  
    cisco.intersight.intersight_rest_api:
      <<: *api_info_mgmt
      resource_path: /vnic/EthNetworkPolicies
      query_params:
         $filter: "Name eq '{{ name_of_network_policy_IB_vlan }}'"
      api_body: {
        "Name": "{{ name_of_network_policy_IB_vlan }}",
        "Description": "{{ description_of_network_policy_IB }}",

        "Organization": {
           "Moid": "{{ intersight_org.api_response.Moid }}"
         },
        Tags: [{Key: "configmode", Value: "ansible"},{Key: "prefix", Value: "{{ prefix }}"}],
        "VlanSettings": {
           "Mode": "TRUNK",
           "DefaultVlan": "{{ ib_vlan_id }}",
           "AllowedVlans": ""
           }
        }
    register: management_network_policy_IB
