---
  # This task sets Ethernet ports to L2 and enables interfaces
  - name: Enabling all ethernet and port-channel interfaces
    cisco.nxos.nxos_interfaces:
      config:
        - name: "{{ item.interface }}"
          description: "{{ item.description }}"
          mode: layer2
          enabled: yes
    with_list: "{{ all_interfaces + all_port_channels }}"

  # This task enables normal UDLD on the UCS-A interfaces
  - name: Enable normal UDLD on the UCS interfaces
    cisco.nxos.nxos_udld_interface:
      interface: "{{ item.interface }}"
      mode: enabled
    with_list: "{{ vDS_interface_list }}"

  # This task adds ports to the peer-link port-channels
  - name: Add Ports to peer-link Port-Channel
    cisco.nxos.nxos_lag_interfaces:
      config:
        - name: "{{ peerlink_PC[0].interface }}"
          members:
            - member: "{{ item.interface }}"
              mode: active
    with_list: "{{ peerlink_interface_list }}"

  # This task adds ports to the uplink switch port-channels
  - name: Add Ports to uplink switch Port-Channel
    cisco.nxos.nxos_lag_interfaces:
      config:
        - name: "{{ uplink_PC[0].interface }}"
          members:
            - member: "{{ item.interface }}"
              mode: active
    with_list: "{{ uplink_interface_list  }}"

  # This task adds ports to the UCS port-channels
  - name: Add Ports to UCS Port-Channel
    cisco.nxos.nxos_lag_interfaces:
      config:
        - name: "{{ item.1.interface }}"
          members:
            - member: "{{ item.0.interface }}"
              mode: active
    with_together: 
      - "{{ vDS_interface_list | flatten}}"
      - "{{ UCS_PC | flatten}}"

  # This task adds ports to the Storage-A port-channels
  - name: Add Ports to Storage-A Port-Channel
    cisco.nxos.nxos_lag_interfaces:
      config:
        - name: "{{ storage_A_PC[0].interface }}"
          members:
            - member: "{{ item.interface }}"
              mode: active
    with_list: "{{ storage_A_interface_list }}"

  # This task adds ports to the Storage-B port-channels
  - name: Add Ports to Storage-B Port-Channel
    cisco.nxos.nxos_lag_interfaces:
      config:
        - name: "{{ storage_B_PC[0].interface }}"
          members:
            - member: "{{ item.interface }}"
              mode: active
    with_list: "{{ storage_B_interface_list }}"
#
# This task sets up speed and duplex settings for the peer link
  - name: Modify the speed and duplex for peer link
    cisco.nxos.nxos_interfaces:
      config:
        - name: "{{ item.interface }}"
          speed: "{{ item.speed }}"
          duplex: "{{ item.duplex }}"
    with_list: "{{ peerlink_PC }}"  
#
# This task sets up speed, duplex and mtu settings for the other interfaces
  - name: Modify the mtu speed and duplex for ports
    cisco.nxos.nxos_interfaces:
      config:
        - name: "{{ item.interface }}"
          mtu: "9216"
          speed: "{{ item.speed }}"
          duplex: "{{ item.duplex }}"
    with_list: "{{ uplink_PC + UCS_PC + storage_A_PC + storage_B_PC }}"
#
  - name: Modify the mtu standalone UCS Nexus ports
    cisco.nxos.nxos_interfaces:
      config:
        - name: "{{ item.interface }}"
          mtu: "9216"
    with_list: "{{ vSwitch_interface_list }}"

# Configure Trunk VLANs for Peer-Link and UCS UCS Port-Channels
#
  - name: Enabling all vlans on peer-link and UCS Port-Channels
    cisco.nxos.nxos_l2_interfaces:
      config:
        - name: "{{ item.interface }}"
          trunk:
            native_vlan: "{{ native_vlan_id }}"
            allowed_vlans: "{{ all_vlans_list }}"
    with_list: "{{ peerlink_PC + UCS_PC + vSwitch_interface_list}}"
#
# Configure VLANs mgmt Port-Channels
#
  - name: Enabling management vlans on uplink Port-Channels
    cisco.nxos.nxos_l2_interfaces:
      config:
        - name: "{{ item.interface }}"
          trunk:
            native_vlan: "{{ native_vlan_id }}"
            allowed_vlans: "{{ mgmt_vlans_list }}"
    with_list: "{{ uplink_PC }}"
#
# Configure VLANs for storage Port-Channels
#
  - name: Enabling storage vlans on Storage Port-Channels
    cisco.nxos.nxos_l2_interfaces:
      config:
        - name: "{{ item.interface }}"
          trunk:
            native_vlan: "{{ native_vlan_id }}"
            allowed_vlans: "{{ storage_vlans_list }}"
    with_list: "{{ storage_A_PC + storage_B_PC }}"
#
# The tasks below are added to overcome issues in Ansible Scripts
# 1) https://github.com/ansible/ansible/issues/64896
# switchport mode trunk is not set correctly and have to be added manually
# 2) Spanning-tree port type edge trunk" on UCS and Storage Port-Channels can not be set using ansible function

  # This task sets:
  # "switchport mode trunk" on all Port-Channels
  - name: Set - switchport mode trunk
    cisco.nxos.nxos_config:
      lines:
        - switchport mode trunk
      parents: interface {{ item.interface }}
    with_list: "{{ all_port_channels + vSwitch_interface_list}}"
  #
  # This task sets:
  # "Spanning-tree port type edge trunk" on UCS and Storage Port-Channels
  - name: Set - spanning-tree port type edge trunk
    cisco.nxos.nxos_config:
      lines:
        - spanning-tree port type edge trunk
      parents: interface {{ item.interface }}
    with_list: "{{ UCS_PC + storage_A_PC + storage_B_PC + vSwitch_interface_list}}"
#
  # This Task sets up fec rs-fec command between UCS-VIC Nexus links
  - name: Configure FEC on UCS-VIC and Nexus links
    cisco.nxos.nxos_config:
      lines: "{{ fec_ucs_nexus_settings }}"
      parents: interface {{ item.interface }}
    with_list: "{{ ucs_nexus_links}}"

  # This task sets:
  # "Spanning-tree port type normal" on the Uplink Port-Channel
  - name: Set - spanning-tree port type normal
    cisco.nxos.nxos_config:
      lines:
        - spanning-tree port type normal
      parents: interface {{ item.interface }}
    with_list: "{{ uplink_PC }}"
