---
# Create Server Profile Template
- name: "Configure Server Profile Template"
  vars:
        api_info: &api_info_assign
          api_private_key: "{{ api_private_key }}"
          api_key_id: "{{ api_key_id }}"
          api_uri: "{{ api_uri | default(omit) }}"
          validate_certs: "{{ validates_certs | default(omit) }}"
          state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_rest_api:
          <<: *api_info_assign
          resource_path: /server/ProfileTemplates
          query_params:
            $filter: "Name eq '{{ name_of_SPT }}'"
          api_body: {
              "Action": "No-op",
              "Name": "{{ name_of_SPT }}",
              "Description": "{{ description_of_SPT }}",
              ClassId: "server.ProfileTemplate",
              "PolicyBucket": [
                {
                  "Moid": "{{ boot_order_policy_details.api_response.Moid }}",
                  "ObjectType": "boot.PrecisionPolicy"
                },
                {
                  "Moid": "{{ vmedia_policy_details.api_response.Moid }}",
                  "ObjectType": "vmedia.Policy"
                },
                {
                  "Moid": "{{ kvm_policy_details.api_response.Moid }}",
                  "ObjectType": "kvm.Policy"
                },
                {
                  "Moid": "{{ ipmi_policy_details.api_response.Moid }}",
                  "ObjectType": "ipmioverlan.Policy"
                },
                {
                  "Moid": "{{ local_user_policy_details.api_response.Moid }}",
                  "ObjectType": "iam.EndPointUserPolicy"
                },
                {
                  "Moid": "{{ networkconfig_policy_details.api_response.Moid }}",
                  "ObjectType": "networkconfig.Policy"
                },
                {
                  "Moid": "{{ ntp_policy_details.api_response.Moid }}",
                  "ObjectType": "ntp.Policy"
                },
                {
                  "Moid": "{{ storage_policy_details.api_response.Moid }}",
                  "ObjectType": "storage.StoragePolicy"
                },
                {
                  "Moid": "{{ bios_policy_details.api_response.Moid }}",
                  "ObjectType": "bios.Policy"
                },
                {
                  "Moid": "{{ lan_connectivity_policy_details.api_response.Moid }}",
                  "ObjectType": "vnic.LanConnectivityPolicy"
                },
                {
                  "Moid": "{{ adapter_policy_details.api_response.Moid }}",
                  "ObjectType": "adapter.ConfigPolicy"
                },
              ],
              "TargetPlatform": "Standalone",
              "Organization": {
                "Moid": "{{ intersight_org.api_response.Moid }}"
              },
              Tags: [{Key: "configmode", Value: "ansible"},{Key: "prefix", Value: "{{ prefix }}"}],
              UuidAddressType: "NONE",
              UuidPool: null
            }
  