---
  - name: Add host to the vDS '{{ dvs_name }}'
    community.vmware.vmware_dvs_host:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: no
      esxi_hostname: '{{ inventory_hostname }}'
      switch_name: '{{ dvs_name }}'
      lag_uplinks:
        - lag: lag1
          vmnics:
              - '{{ dv_uplink1 }}'
              - '{{ dv_uplink2 }}'
      state: present
    delegate_to: localhost

