# Configure various ESXi host settings
#
# ESXi must have been installed and IP/Password/DNS/DNS Domain configured for mgmt access
# SSH must be enabled on the ESXi host
#Disable esxi ipv6 of the ESXi hosts
  - include_tasks: disable_esxi_ipv6.yml
#Modify DNS
  - include_tasks: modify_esxi_dns.yml
# Add the NTP Server(s) to the ESXi Hosts
  - include_tasks: add_esxi_ntp.yml
# Modify the vSwitch0 for ESXi Hosts to add redundant NIC and set MTU to 9000
  - include_tasks: modify_esxi_vswitch0.yml
# Create the IB-MGMT Network Portgroup
  - include_tasks: create_esxi_ib_mgmt_PG.yml
# Create the NFS Portgroup
  - include_tasks: create_esxi_nfs_PG.yml
# Create NFS VMK
  - include_tasks: add_esxi_nfs_vmk.yml
# Add NFS Datastores
  - include_tasks: add_esxi_nfs_datastores.yml
# Upgrade or Install VIC Drivers, NetApp NFS VAAI Plugin, and UCS Tools
 - include_tasks: upgrade_ESXi_drivers.yml
